# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import video_streaming_service_pb2 as video__streaming__service__pb2


class video_streamer_handlerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.send_image_chunk = channel.unary_unary(
                '/video_streamer.video_streamer_handler/send_image_chunk',
                request_serializer=video__streaming__service__pb2.Empty.SerializeToString,
                response_deserializer=video__streaming__service__pb2.image_chunk.FromString,
                )
        self.send_slam_points = channel.unary_unary(
                '/video_streamer.video_streamer_handler/send_slam_points',
                request_serializer=video__streaming__service__pb2.Empty.SerializeToString,
                response_deserializer=video__streaming__service__pb2.slam_points_package.FromString,
                )


class video_streamer_handlerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def send_image_chunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def send_slam_points(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_video_streamer_handlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'send_image_chunk': grpc.unary_unary_rpc_method_handler(
                    servicer.send_image_chunk,
                    request_deserializer=video__streaming__service__pb2.Empty.FromString,
                    response_serializer=video__streaming__service__pb2.image_chunk.SerializeToString,
            ),
            'send_slam_points': grpc.unary_unary_rpc_method_handler(
                    servicer.send_slam_points,
                    request_deserializer=video__streaming__service__pb2.Empty.FromString,
                    response_serializer=video__streaming__service__pb2.slam_points_package.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'video_streamer.video_streamer_handler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class video_streamer_handler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def send_image_chunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/video_streamer.video_streamer_handler/send_image_chunk',
            video__streaming__service__pb2.Empty.SerializeToString,
            video__streaming__service__pb2.image_chunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def send_slam_points(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/video_streamer.video_streamer_handler/send_slam_points',
            video__streaming__service__pb2.Empty.SerializeToString,
            video__streaming__service__pb2.slam_points_package.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
