# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_streaming_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dvideo_streaming_service.proto\x12\x0evideo_streamer\"\x1c\n\x0bimage_chunk\x12\r\n\x05image\x18\x01 \x01(\x0c\".\n\x0bslam_points\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"C\n\x13slam_points_package\x12,\n\x07payload\x18\x01 \x03(\x0b\x32\x1b.video_streamer.slam_points\"\x07\n\x05\x45mpty2\xb0\x01\n\x16video_streamer_handler\x12\x46\n\x10send_image_chunk\x12\x15.video_streamer.Empty\x1a\x1b.video_streamer.image_chunk\x12N\n\x10send_slam_points\x12\x15.video_streamer.Empty\x1a#.video_streamer.slam_points_packageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_streaming_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGE_CHUNK._serialized_start=49
  _IMAGE_CHUNK._serialized_end=77
  _SLAM_POINTS._serialized_start=79
  _SLAM_POINTS._serialized_end=125
  _SLAM_POINTS_PACKAGE._serialized_start=127
  _SLAM_POINTS_PACKAGE._serialized_end=194
  _EMPTY._serialized_start=196
  _EMPTY._serialized_end=203
  _VIDEO_STREAMER_HANDLER._serialized_start=206
  _VIDEO_STREAMER_HANDLER._serialized_end=382
# @@protoc_insertion_point(module_scope)
